In [14]:
import pandas as pd
df = pd.read_csv("Cars93.csv", na_values = ["", "NA"], keep_default_na= False)
df.head()

,id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
0,1,Acura,Integra,Small,12.9,15.9,18.8,25,31,None,...,5,177,102,68,37,26.5,11.0,2705,non-USA,Acura Integra
1,2,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver & Passenger,...,5,195,115,71,38,30.0,15.0,3560,non-USA,Acura Legend
2,3,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,...,5,180,102,67,37,28.0,14.0,3375,non-USA,Audi 90
3,4,Audi,100,Midsize,30.8,37.7,44.6,19,26,NaN,...,6,193,106,70,37,31.0,17.0,3405,non-USA,Audi 100
4,5,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,...,4,186,109,69,39,27.0,13.0,3640,non-USA,BMW 535i

In [15]:
####Perform basic quality checks######

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 28 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  93 non-null     int64
 1   Manufacturer        93 non-null     object
 2   Model               93 non-null     object
 3   Type                93 non-null     object
 4   Min.Price           93 non-null     float64
 5   Price               93 non-null     float64
 6   Max.Price           93 non-null     float64
 7   MPG.city            93 non-null     int64
 8   MPG.highway         93 non-null     int64
 9   AirBags             89 non-null     object
 10  DriveTrain          93 non-null     object
 11  Cylinders           93 non-null     object
 12  EngineSize          93 non-null     float64
 13  Horsepower          93 non-null     int64
 14  RPM                 93 non-null     int64
 15  Rev.per.mile        93 non-null     int64
 16  Man.trans.avail     93 non-null     object
 17  Fuel.tank.capacity  93 non-null     float64
 18  Passengers          93 non-null     int64
 19  Length              93 non-null     int64
 20  Wheelbase           93 non-null     int64
 21  Width               93 non-null     int64
 22  Turn.circle         93 non-null     int64
 23  Rear.seat.room      91 non-null     float64
 24  Luggage.room        82 non-null     float64
 25  Weight              93 non-null     int64
 26  Origin              93 non-null     object
 27  Make                93 non-null     object
dtypes: float64(7), int64(12), object(9)
memory usage: 20.5+ KB

In [17]:
df.isna().sum()

id                     0
Manufacturer           0
Model                  0
Type                   0
Min.Price              0
Price                  0
Max.Price              0
MPG.city               0
MPG.highway            0
AirBags                4
DriveTrain             0
Cylinders              0
EngineSize             0
Horsepower             0
RPM                    0
Rev.per.mile           0
Man.trans.avail        0
Fuel.tank.capacity     0
Passengers             0
Length                 0
Wheelbase              0
Width                  0
Turn.circle            0
Rear.seat.room         2
Luggage.room          11
Weight                 0
Origin                 0
Make                   0
dtype: int64

In [18]:
m = df.isna().sum()

In [19]:
m

id                     0
Manufacturer           0
Model                  0
Type                   0
Min.Price              0
Price                  0
Max.Price              0
MPG.city               0
MPG.highway            0
AirBags                4
DriveTrain             0
Cylinders              0
EngineSize             0
Horsepower             0
RPM                    0
Rev.per.mile           0
Man.trans.avail        0
Fuel.tank.capacity     0
Passengers             0
Length                 0
Wheelbase              0
Width                  0
Turn.circle            0
Rear.seat.room         2
Luggage.room          11
Weight                 0
Origin                 0
Make                   0
dtype: int64

In [20]:
m[m>0]

AirBags            4
Rear.seat.room     2
Luggage.room      11
dtype: int64

In [21]:
df.duplicated().sum()

np.int64(0)

In [22]:
####Drop Duplicates####

In [23]:
df = df.drop_duplicates(keep="first")

In [24]:
m[m>0]

AirBags            4
Rear.seat.room     2
Luggage.room      11
dtype: int64

In [25]:
######Replace missing values #########

In [26]:
df["AirBags"].value_counts()

AirBags
Driver only           42
None                  33
Driver & Passenger    14
Name: count, dtype: int64

In [27]:
#Calculating mode for categorical coulmns
mode = df["AirBags"].mode()[0]

In [28]:
#Calculating mean for numerical coulmns
df["Luggage.room"].mean()

np.float64(13.890243902439025)

In [29]:
#Calculating me fodianr numerical coulmns
df["Luggage.room"].median()

np.float64(14.0)

In [30]:
#Using fillna to replace missing values

df["AirBags"] = df["AirBags"].fillna(mode)

In [31]:
df["AirBags"].isna().sum()

np.int64(0)

In [32]:
df.isna().sum()

id                     0
Manufacturer           0
Model                  0
Type                   0
Min.Price              0
Price                  0
Max.Price              0
MPG.city               0
MPG.highway            0
AirBags                0
DriveTrain             0
Cylinders              0
EngineSize             0
Horsepower             0
RPM                    0
Rev.per.mile           0
Man.trans.avail        0
Fuel.tank.capacity     0
Passengers             0
Length                 0
Wheelbase              0
Width                  0
Turn.circle            0
Rear.seat.room         2
Luggage.room          11
Weight                 0
Origin                 0
Make                   0
dtype: int64

In [21]:
#Function for replacing

def replacer(df):
     cat = list(df.columns[df.dtypes == "object"])
     for i in df.columns:
          if i in cat:
              mode = df[i].mode()[0]
              df[i] = df[i].fillna(mode)
          else:
               mean = df[i].mean()
               df[i] = df[i].fillna(mean)

print("Missing values are replaced")

Missing values are replaced

In [22]:
replacer(df)

In [23]:
df.isna().sum()

id                    0
Manufacturer          0
Model                 0
Type                  0
Min.Price             0
Price                 0
Max.Price             0
MPG.city              0
MPG.highway           0
AirBags               0
DriveTrain            0
Cylinders             0
EngineSize            0
Horsepower            0
RPM                   0
Rev.per.mile          0
Man.trans.avail       0
Fuel.tank.capacity    0
Passengers            0
Length                0
Wheelbase             0
Width                 0
Turn.circle           0
Rear.seat.room        0
Luggage.room          0
Weight                0
Origin                0
Make                  0
dtype: int64

In [24]:
#saving this into another csv file

df.to_csv("Cars_cleaned.csv", index = False)

In [25]:
###Seperate X and Y

# Y - Weight(Target)
# X - Remaining Columns (Independent Features)

x = df.drop(columns= ["id", "Weight"])
y = df[["Weight"]]

In [26]:
x.head()

  Manufacturer    Model     Type  ...  Luggage.room   Origin           Make
0        Acura  Integra    Small  ...          11.0  non-USA  Acura Integra
1        Acura   Legend  Midsize  ...          15.0  non-USA   Acura Legend
2         Audi       90  Compact  ...          14.0  non-USA        Audi 90
3         Audi      100  Midsize  ...          17.0  non-USA       Audi 100
4          BMW     535i  Midsize  ...          13.0  non-USA       BMW 535i

[5 rows x 26 columns]

In [27]:
y.head()

   Weight
0    2705
1    3560
2    3375
3    3405
4    3640

In [28]:
###Converting catogerical data into numeric data

#We separated categorical data first
x_cat = df.select_dtypes(include = "object")
x_cat.head()

  Manufacturer    Model     Type  ... Man.trans.avail   Origin           Make
0        Acura  Integra    Small  ...             Yes  non-USA  Acura Integra
1        Acura   Legend  Midsize  ...             Yes  non-USA   Acura Legend
2         Audi       90  Compact  ...             Yes  non-USA        Audi 90
3         Audi      100  Midsize  ...             Yes  non-USA       Audi 100
4          BMW     535i  Midsize  ...             Yes  non-USA       BMW 535i

[5 rows x 9 columns]

In [29]:
#Separating continuos data

x_con = df.select_dtypes(exclude= "object")
x_con.head()

   id  Min.Price  Price  ...  Rear.seat.room  Luggage.room  Weight
0   1       12.9   15.9  ...            26.5          11.0    2705
1   2       29.2   33.9  ...            30.0          15.0    3560
2   3       25.9   29.1  ...            28.0          14.0    3375
3   4       30.8   37.7  ...            31.0          17.0    3405
4   5       23.7   30.0  ...            27.0          13.0    3640

[5 rows x 19 columns]

In [30]:
# Applying One Hot Encoding

from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(handle_unknown = "ignore", sparse_output= False).set_output(transform= "pandas")
x_cat_pre = ohe.fit_transform(x_cat)
x_cat_pre.head()

   Manufacturer_Acura  Manufacturer_Audi  ...  Make_Volvo 240  Make_Volvo 850
0                 1.0                0.0  ...             0.0             0.0
1                 1.0                0.0  ...             0.0             0.0
2                 0.0                1.0  ...             0.0             0.0
3                 0.0                1.0  ...             0.0             0.0
4                 0.0                0.0  ...             0.0             0.0

[5 rows x 240 columns]

In [31]:
#### Scaling down of numerical data

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler().set_output(transform = "pandas")
x_con_pre = scaler.fit_transform(x_con)
x_con_pre.head()

         id  Min.Price     Price  ...  Rear.seat.room  Luggage.room    Weight
0 -1.713526  -0.485787 -0.375720  ...       -0.452197     -1.033015 -0.627055
1 -1.676275   1.388017  1.497844  ...        0.738090      0.396643  0.830208
2 -1.639025   1.008658  0.998227  ...        0.057926      0.039228  0.514894
3 -1.601774   1.571949  1.893374  ...        1.078172      1.111472  0.566026
4 -1.564523   0.755752  1.091905  ...       -0.282156     -0.318186  0.966560

[5 rows x 19 columns]

In [32]:
#Combine cat and con data

processed = x_con_pre.join(x_cat_pre)
processed.head()

         id  Min.Price  ...  Make_Volvo 240  Make_Volvo 850
0 -1.713526  -0.485787  ...             0.0             0.0
1 -1.676275   1.388017  ...             0.0             0.0
2 -1.639025   1.008658  ...             0.0             0.0
3 -1.601774   1.571949  ...             0.0             0.0
4 -1.564523   0.755752  ...             0.0             0.0

[5 rows x 259 columns]

In [33]:
processed.to_csv("Cars_processed.csv", index=  False)

 Train Test Split

In [39]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(processed, y, test_size = 0.2)

In [40]:
xtrain.head()

          id  Min.Price  ...  Make_Volvo 240  Make_Volvo 850
23 -0.856763  -1.003095  ...             0.0             0.0
13 -1.229268  -0.428309  ...             0.0             0.0
85  1.452772  -0.221386  ...             0.0             0.0
87  1.527273  -0.968608  ...             0.0             0.0
67  0.782262  -0.474292  ...             0.0             0.0

[5 rows x 259 columns]

In [41]:
ytrain.head()

    Weight
23    2670
13    3240
85    3030
87    2240
67    2910

In [42]:
df["Weight"].describe()

LinearRegression()

In [44]:
model.score(xtrain, ytrain)

1.0

Testing the model

In [45]:
from sklearn.metrics import(
    root_mean_squared_error,
    mean_absolute_error,
    mean_absolute_percentage_error,
    r2_score
)

In [46]:
def evaluate_model(model, x, y):
    #predict the results
    ypred = model.predict(x)
    #evalutate 
    rmse = root_mean_squared_error(y, ypred)
    mae = mean_absolute_error(y, ypred)
    mape = mean_absolute_percentage_error(y, ypred)
    r2 = r2_score(y, ypred)

    #print results
    print(f"Rmse : {rmse}")
    print(f"mae : {mae}")
    print(f"mape : {mape}")
    print(f"r2 : {r2}")

In [47]:
#Training results
evaluate_model(model, xtrain, ytrain)

Rmse : 6.210032329319103e-13
mae : 4.547473508864641e-13
mape : 1.5711946765184416e-16
r2 : 1.0

In [48]:
#Testing results
evaluate_model(model, xtest, ytest)

Rmse : 104.02062798289312
mae : 75.76154932949993
mape : 0.023600753384665964
r2 : 0.978806627423162